<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0ff35cf0-7370-423f-a8cb-d7887e4dcf2d</elementGuidId>
    <imagePath></imagePath>
    <name>label_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for='\31 52170-case-633']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-outline-secondary')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-outline-secondary</value>
        <webElementGuid>113b3f69-ddf7-4c9c-a6bf-764e6a5181f5</webElementGuid>
    </webElementProperties>
</WebElementEntity>